---
- name: Copy script to remote machine
  copy:
    src: "{{ item }}"
    dest: /root/
    owner: root
    group: root
    mode: '0555'
  with_items:
    - smallfile-test-for-fuse.sh
    - sync-and-drop-cache.yml
    - ansible.cfg
    - largefile-test-for-fuse.sh
    - largefile-test-for-fuse-with-fio.sh
    - collect-info.sh
    - fio-config-files/sequential-read.fio
    - fio-config-files/sequential-write.fio
    - fio-config-files/random-read.fio
    - fio-config-files/random-write.fio

- name: Copy inventroy file with the name hosts
  copy:
    src: "{{ inventory_file }}"
    dest: /root/hosts
    owner: root
    group: root
    mode: '0555'

- name: Commenting vault pass line
  lineinfile:
    path: /root/ansible.cfg
    regexp: '^vault_password_file[.]*'
    line: '#vault_password_file'
    backrefs: yes

- name: Create config scripts
  template:
    src: templates/client.j2
    dest: /root/client.ioz
    mode: '0644'

- name: Setting up ssh config
  lineinfile:
    path: /etc/ssh/ssh_config
    line: "{{ item }}"
    insertbefore: BOF
  with_items:
    - 'StrictHostKeyChecking=no'
    - 'UserKnownHostsFile="/dev/null"'

- name: delete the logs of any previous runs
  file:
    path: "/root/{{ item }}"
    state: absent
  with_items:
    - /root/PerfTest.log
    - /root/fuse-smallfile-result.txt
    - /root/fuse-smallfile-profile
    - /root/fuse-smallfile-profile.tar
    - /root/fuse-iozone-result.txt
    - /root/fuse-largefile-profile-iozone
    - /root/fuse-largefile-profile-iozone.tar
    - /root/fuse-fio-result.tar
    - /root/fuse-fio-output.txt

- name: Run smallfile test
  shell: "/root/smallfile-test-for-fuse.sh \"{{node0}}\"  > /root/fuse-smallfile-result.txt 2>&1"
  async: 32400                                 # waiting for 9 hours for test to complete, if it finishes early poll will detect that and report
  poll: 900
  register: perf_test
  when: tool == "smallfile"

- name: Run largefile test using izone
  shell: "/root/largefile-test-for-fuse.sh \"{{node0}}\" \"{{total_number_of_threads}}\" > /root/fuse-iozone-result.txt 2>&1"
  async: 32400                                 # waiting for 9 hours for test to complete, if it finishes early poll will detect that and report
  poll: 900
  register: perf_test
  when: tool == "iozone"

- name: Run largefile test using fio
  shell: "/root/largefile-test-for-fuse-with-fio.sh \"{{node0}}\"  > /root/fuse-fio-output.txt 2>&1"
  async: 32400                                 # waiting for 9 hours for test to complete, if it finishes early poll will detect that and report
  poll: 900
  register: perf_test
  when: tool == "fio"

- name: fetch a file from remote machine
  fetch:
    src: "{{ item }}"
    dest: "{{ download_results_at_location }}/results/"
    flat: yes
  with_items:
    - /root/fuse-smallfile-result.txt
    - /root/PerfTest.log
    - /root/fuse-smallfile-profile.tar
    - /root/fuse-iozone-result.txt
    - /root/fuse-fio-result.tar
    - /root/fuse-largefile-profile-iozone.tar
  ignore_errors: yes
